name = "api"
compatibility_date = "2025-04-03"
compatibility_flags = ["nodejs_compat_v2"]
main = "./functions/index.js"

[assets]
binding = "ASSETS"
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/*"]

[[kv_namespaces]]
binding = "YTMUSIC_SITEMAP_KV"
id = "f9dd3de5bd0e45cf96a5158cd1c56a9c"

[dev]
port = 3000
